app:
    extends:
        file: docker-compose.common.yml
        service: app
    links:
        - mongo
        - redis

redis:
    image: redis:latest

mongo:
    extends:
        file: docker-compose.common.yml
        service: mongo
