app:
    extends:
        file: docker-compose.common.yml
        service: app
    volumes:
        - flask_desk:/code/flask_desk
    links:
        - mongo
mongo:
    extends:
        file: docker-compose.common.yml
        service: mongo
