#!/bin/sh

set -ex;

image_name=rcelha/flask_desk_application
container_name=rcelha_flask_desk_application_run
prev=`docker images -q ${image_name}`

echo Build docker image;
docker-compose -f docker-compose.prod.yml stop
docker-compose -f docker-compose.prod.yml rm --force app
docker build -t ${image_name} .
docker rmi ${prev}
